### ISSUE TITLE
Roots don't get created when loading an existing database

### ISSUE THREAD

**Issue by geoffreylitt** [SkipLabs/skdb#14]
If I load an existing database from persistence, and then call `addRoot` to add a root for a tracked function, the root is not added to SKDB's list of roots, and I can't get its value.

This seems like a bug, or maybe I'm misunderstanding the API.

I can't tell much about intended behavior from the JS wrapper because most of the logic is inside WASM.

## repro

This code creates 2 new DBs and has no problem adding roots.

Then it loads an existing DB and tries to add a root, but the root seems to not get added.

```js
import { SKDB } from 'skdb'

const createDBWithRoot = async (name) => {
  const db = await SKDB.create(name)
  const callable = db.registerFun(() => 'hello')
  const rootId = Math.random().toString(36).slice(0, 5)
  db.addRoot(rootId, callable, {})
  console.log(`DB ${name} has ${[...db.roots.keys()].length} roots:`, db.roots)
}

// create new DBs
createDBWithRoot('db1')
createDBWithRoot('db2')

// load existing DB
createDBWithRoot('db1')
```

output:

```
DB db1 has 1 roots: Map(1) {'0.5z0' => '"hello"'}
DB db2 has 1 roots: Map(1) {'0.1q0' => '"hello"'}
DB db1 has 0 roots: Map(0) {size: 0}
```

## live version

If you go to this webpage and open the console log you'll see the output above:

https://skdb-bug-repro.geoffreylitt.repl.co/

Note, it only works the first time; after you reload all DBs have 0 roots because of this issue. If you clear site data and IDB then you can see the repro again

(Technically `db.roots` is private state within SKDB, but all `getRoot` does is get the value from the `db.roots` map)

**Comment by gregsexton** [comment]
Fixed. My previous fix didn't cover reloading the db. I'll cut a new npm pkg for you now.

**Comment by geoffreylitt** [comment]
When I run the repro code above on 0.0.39, it still produces the same result as before, so I'm not sure the issue has been fixed.

Code: https://replit.com/@GeoffreyLitt/SKDB-bug-repro#main.js
Running code, output in console: https://skdb-bug-repro.geoffreylitt.repl.co/

The last line still prints `DB db1 has 0 roots: Map(0) {size: 0}` as above, whereas I'd expect it to print `DB db1 has 1 roots: ...`.

Curious if that repro makes sense to you?

**Comment by gregsexton** [comment]
We're going to need to debug something here, because this is what I see:
<img width="976" alt="image" src="https://github.com/SkipLabs/skdb/assets/150883/a869ae44-5e50-466a-bd87-d50df7bc1f5f">

**Comment by gregsexton** [comment]
Running:  https://skdb-bug-repro.geoffreylitt.repl.co/

**Comment by geoffreylitt** [comment]
Thanks I see the fix working now!
