### ISSUE TITLE
Please split up the `skdb` package into `skdb` (for Browser) and `skdb-node` (for Node.js)

### ISSUE THREAD

**Issue by schickling** [SkipLabs/skdb#5]
I'd suggest to split up the currently single `skdb` package into two separate packages `skdb` (for Browser) and `skdb-node` or similar (for Node.js) given the Node version has many Node.js specific dependencies that the browser version doesn't have.

Related: #4

**Comment by gregsexton** [comment]
Dup of #4. I'll resolve this probably today.
