### ISSUE TITLE
Count aggregation in view

### ISSUE THREAD

**Issue by schickling** [SkipLabs/skdb#6]
![CleanShot 2023-04-25 at 10 11 39@2x](https://user-images.githubusercontent.com/1567498/234215730-2bbef1f8-2c2c-4349-9864-9187e29c20ba.png)

Repro queries:

```sql

select * from view__tracks_playlists where playlistId = 'podcast:playlist:clgvzc2jr000d3b68fnorg3lm';
-- correctly returns 460 items
select  trackCount from view__playlists_with_track_counts where id = 'podcast:playlist:clgvzc2jr000d3b68fnorg3lm';
-- wrongly returns `trackCount: 78`
```

SQL Dump:

[dump.sql.zip](https://github.com/SkipLabs/skdb/files/11320257/dump.sql.zip)

**Comment by pikatchu** [comment]
The problem is that your join is the other way around. You should write this, joining view__tracks_playlist with library_playlists, not the other way around.
```
SELECT _p.id, _tp.trackId as trackCount
      FROM view__tracks_playlists AS _tp
      LEFT OUTER JOIN library_playlists AS _p ON _p.id = _tp.playlistId 
```
